on:
  push:
    branches:
      - develop
name: "Build and Release ANDR"
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/flutter-action@v1
      - run: flutter pub get
      - run: flutter test
