name: test-my-app
# on: [push, workflow_dispatch]
on: [pull_request, workflow_dispatch]
# on:
#   pull_request:
#     types: [opened, reopened]
#     branches:
#       - develop
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    
    - name: Restore Package
      run: flutter pub get
      
    - name: Install Realm Dart
      run: dart run realm_dart install
      
    - name: Run Build Runner
      run: dart run build_runner build test --delete-conflicting-outputs
      
    - name: Run Test
      run: flutter test --coverage

    # - name: Upload coverage to codecov
    #   run: curl -s https://codecov.io/bash
    #   shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
