name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    
    - name: Restore Package
      run: flutter pub get
      
    - name: Install Realm Dart
      run: dart run realm_dart install
      
    - name: Run Build Runner
      run: dart run build_runner build test --delete-conflicting-outputs
      
    - name: Analyze
      run: flutter analyze
      
    - name: Run Test
      run: flutter test --coverage
    
