name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run realm_dart install
    - run: dart run build_runner build test
    - run: flutter test
